### PR TITLE
Add security exception for /job/*/build and /job/*/buildWithParameters

### PR DESCRIPTION
**Pull request by fancyremarker**
This pull request adds a configuration option to expose the `/build` and `/buildWithParameters` URLs for all jobs.

In order to trigger builds remotely (via "Build Triggers"), an external client needs to make a request to `/job/:job-name/build` (or `/job/:job-name/buildWithParameters`). This request is protected by a secret `token` parameter, so exposing the URL publicly should be minimally dangerous.

### CODE REVIEW

**Comment by mbbx6spp** [comment]
+1 This works on my Jenkins master installation and before I was getting the annoying `<meta http-equiv='refresh' content='1;url=/securityRealm/commenceLogin?from=...` response using my API token. Thanks @macreery, you made my day :)

**Comment by mocleiri** [comment]
Thanks for your contribution.

I don't have time to maintain this plugin anymore but if you send mail to the jenkins dev mailing list you can get commit access to the jenkinsci fork where you can make a new release containing this change and get it released in a way where others can download it through the jenkins plugin download mechanism.

**Comment by bhardin** [comment]
@macreery Would you be willing to send an email to get this in? It would benefit me greatly.

@mocleiri I hope the new baby is well. ;)

**Comment by fancyremarker** [comment]
Hey @bhardin – it seems as though someone has already forked this repo at [jenkinsci/github-oauth-plugin](/jenkinsci/github-oauth-plugin), and that is now the canonical fork from which official plugin releases are made. I've reopened this pull request there as jenkinsci/github-oauth-plugin#7.

**Comment by fancyremarker** [comment]
@bhardin – also, in case it's easier/better for you to not have to wait for an official plugin release, you can build this plugin locally, via something like:

```
git clone git://github.com/mocleiri/github-oauth-plugin.git
git pull git://github.com/macreery/github-oauth-plugin.git allow-build-permission
mvn
```

This will produce an HPI archive at `target/github-oauth.hpi`, which you can install manually in Jenkins by browsing to /pluginManager/advanced and choosing "Upload Plugin."

If you'd rather not build it yourself locally, I've posted the .hpi at http://static.artsy.net/misc/github-oauth.hpi.

**Comment by bhardin** [comment]
@macreery Thank you so much. I appreciate you doing this work.

**Comment by bhardin** [comment]
So, I've attempted to use your hpi and build my own. They install fine, but the remote hooks aren't working.

I've tried both url's for building.

```
JENKINS_URL/job/JOB_ID/build?token=TOKEN_NAME 
JENKINS_URL/buildWithParameters?token=TOKEN_NAME
```

Both return the same error as before:

```
<html><head><meta http-equiv='refresh' content='1;url=/securityRealm/commenceLogin?from=%2FbuildWithParameters%3Ftoken%3Dkeepitsimple'/><script>window.location.replace('/securityRealm/commenceLogin?from=%2FbuildWithParameters%3Ftoken%3Dkeepitsimple');</script></head><body style='background-color:white; color:white;'>Authentication required</body></html>
```

Any idea what could be causing the issue?

**Comment by fancyremarker** [comment]
@bhardin – weird, seems as though the security bypass included in this pull request isn't getting hit. Just to make sure this custom build of the plugin is getting loaded, can you confirm that when you visit `/pluginManager`, it lists the "Installed" version of the Github OAuth Plugin as `0.13-SNAPSHOT`?

Assuming it does, are there any exceptions in your `jenkins.log` when you try to hit the URLs?

**Pull request closed without merging**
