### PR TITLE
Restores basic api authentication functionality

### PR DESCRIPTION
**Pull request by luisfaceira**
I've prevented the unhandled exceptions and converted them
into standard exceptions. This way, it seems that the basic auth
filter catches the exceptions and validates the api token, solving issue #18

### CODE REVIEW

**Comment by patcon** [comment]
:+1:

**Comment by mocleiri** [comment]
Thanks for your patch.

I'm having trouble verifying that it works.  I applied it and then ran the maven hpi plugin run goal but I get 403 errors when I try to connect to http://127.0.0.1:8080/job/test/build?token=XYZ in a different browser and wget.

What was the test case you used to validate your patch?

**Comment by luisfaceira** [comment]
Before the change, any request to the api such as http://127.0.0.1:8080/api/json would result on an error.

After the change, I tried request to that url (using curl) and it worked fine. Tried with wrong auth, and got a 404, tried with right api key and it responded json.

To verify that the githuboauth didn't stop working, logged out of github and tried accessing the page with a non-authed github user, and i wasn't able to login, as expected.

example of a curl call:

```
 curl -u user:jenkins_api_token http://localhost:8080/api/json
```

**Comment by michaeldauria** [comment]
To see your jenkins api token, which is different than the github one, do this:

The API token is available in your personal configuration page. Click your name on the top right corner on every page, then click "Configure" to see your API token

**Pull request merged**
