### PR TITLE
Added security exception for cc.xml

### PR DESCRIPTION
**Pull request by apcj**
Open a hole in security to allow unauthenticated access to `/cc.xml` at the root of the server.
This URI provides [monitoring capability](https://wiki.jenkins-ci.org/display/JENKINS/Monitoring+Jenkins) to a range of desktop clients.

This pull request also contains a few minor fixes to the URI matching for all security exceptions to make them more accurate, thereby improving security. For example, prior to this change it was possible to access information about any project with a name containing the string "github-webhook".

### CODE REVIEW

**Comment by mocleiri** [comment]
Thanks for your contribution.

I need to test your changes but if everything works i will cut the 0.11 release this weekend so you can use your changes in production.

**Comment by apcj** [comment]
Great! Let me know if you have any problems and I'll see if I can help.

**Comment by mocleiri** [comment]
Your change is now available in the 0.11 release of the plugin.  Thanks again for your contribution.

**Comment by apcj** [comment]
Perfect!

**Pull request merged**
